### ISSUE TITLE
incorrect error handling for SDL_ShowCursor

### ISSUE THREAD

**Issue by Rainb0wSkeppy** [avaxar/dsdl#2]
`setCursorVisibility` checks if the return value from `SDL_ShowCursor` isnt 0
```
if (SDL_ShowCursor(visible ? SDL_ENABLE : SDL_DISABLE) != 0) {
```
[the sdl docs](https://wiki.libsdl.org/SDL2/SDL_ShowCursor) says that `SDL_ShowCursor` return a negative error code on failure

also please release a new version after fixing this

**Comment by avaxar** [comment]
Done. Thanks for the report.
